name: Deploy Discord Bot

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    permissions:
      actions: none
      attestations: none
      checks: none
      contents: none
      deployments: none
      id-token: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: SSH and deploy bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/kami-music-bot

            # Stop the current container
            docker compose down discord-bot

            # Pull the latest changes
            git pull

            # Rebuild and start the container
            docker compose up -d --build discord-bot